# Generated by Django 4.0.10 on 2023-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
