# Generated by Django 4.0.10 on 2023-12-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_translation_predictionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='predictionId',
            new_name='original_text_id',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='text_id',
            new_name='translated_text_id',
        ),
    ]
