# Generated by Django 4.0.10 on 2023-12-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_predictionid_translation_original_text_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
